name: sora_sdk
description: Flutter plugin for Sora powered by libwebrtc-c.
version: 2026.1.0-canary.0
repository: https://github.com/shiguredo/sora-flutter-sdk

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  # Runtime
  ffi: ^2.2.0
  meta: ^1.16.0
  web_socket_channel: ^3.0.3

  # Scripts
  crypto: ^3.0.6
  hooks: ^2.0.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  archive: ^4.0.2

flutter:
  config:
    enable-swift-package-manager: true
  plugin:
    platforms:
      android:
        package: jp.shiguredo.sora_sdk
        pluginClass: SoraSdkPlugin
      ios:
        pluginClass: SoraSdkPlugin
      macos:
        pluginClass: SoraSdkPlugin
      linux:
        pluginClass: SoraSdkPlugin
      windows:
        pluginClass: SoraSdkPluginCApi
