// GENERATED BY scripts/generate_sdk_version.dart - DO NOT EDIT
// ignore_for_file: public_member_api_docs
// sdk version: 2026.1.0-canary.0
// libwebrtc_c version: 0.150.3
class SoraSDKVersionGen {
  static const String sdkVersion = '2026.1.0-canary.0';
  static const String libwebrtc = 'Shiguredo-Build M150';
}
