import 'dart:convert';
import 'dart:io';

/// scripts/generate_sdk_version.dart
///
/// pubspec.yaml の version と scripts/native_deps.json の libwebrtc_c.version
/// から lib/src/sora_sdk_version.g.dart を生成する。
///
/// 使用方法:
///   dart scripts/generate_sdk_version.dart [package_root]
///
/// package_root を省略した場合はカレントディレクトリが使われる。
void main(List<String> args) async {
  final packageRoot = args.isNotEmpty ? args[0] : Directory.current.path;
  await generateSdkVersionFile(packageRoot);
}

/// バージョン情報を読み取り、.g.dart ファイルを生成する。
Future<void> generateSdkVersionFile(String packageRoot) async {
  final pubspecPath = '$packageRoot/pubspec.yaml';
  final nativeDepsPath = '$packageRoot/scripts/native_deps.json';
  final gDartPath = '$packageRoot/lib/src/sora_sdk_version.g.dart';

  final pubspecContent = await File(pubspecPath).readAsString();
  final sdkVersion = _parsePubspecVersion(pubspecContent);

  final nativeDeps =
      jsonDecode(await File(nativeDepsPath).readAsString())
          as Map<String, dynamic>;
  final libwebrtcC = nativeDeps['libwebrtc_c'] as Map<String, dynamic>;
  final libwebrtcCVersion = libwebrtcC['version'] as String;
  final minorVersion = libwebrtcCVersion.split('.')[1];

  await File(gDartPath).writeAsString(
    '// GENERATED BY scripts/generate_sdk_version.dart - DO NOT EDIT\n'
    '// ignore_for_file: public_member_api_docs\n'
    '// sdk version: $sdkVersion\n'
    '// libwebrtc_c version: $libwebrtcCVersion\n'
    'class SoraSDKVersionGen {\n'
    "  static const String sdkVersion = '$sdkVersion';\n"
    "  static const String libwebrtc = 'Shiguredo-Build M$minorVersion';\n"
    '}\n',
  );
  stderr.writeln('Generated: $gDartPath');
}

/// pubspec.yaml から version フィールドを抽出する。
String _parsePubspecVersion(String content) {
  for (final line in content.split('\n')) {
    final trimmed = line.trim();
    if (trimmed.startsWith('version:')) {
      return trimmed.substring('version:'.length).trim();
    }
  }
  throw FormatException('version field not found in pubspec.yaml');
}
